# Blueprint Configuration
# This file configures the UI mode and ports for the model service

# model_source can be one of the following: local, hugging-face-cloud, or hugging-face-local
model_source: "local"

# Proxy is used to set the HTTPS_PROXY environment variable when necessary.
# For example, if you need to access external services from a restricted network,
# you should specify the proxy in this config.yaml file.
# proxy: "http://web-proxy.austin.hp.com:8080"

# UI Configuration
ui:
  # UI mode: gradio, streamlit, or static
  mode: "streamlit"

# Port Configuration  
ports:
  # External port exposed by Envoy proxy
  external: 5000
  
  # Internal port mappings for different UI types
  internal:
    gradio: 7860
    streamlit: 8501
    static: 5001

# Service Configuration
service:
  # MLflow model server timeout (seconds)
  mlflow_timeout: 600
  
  # Health check timeout for service startup (seconds)
  health_check_timeout: 600
  
  # Number of health check retries
  health_check_retries: 5