# model_source can be one of the following: local, hugging-face-cloud, or hugging-face-local
model_source: "local"

# Azure DevOps Wiki Data Source Configuration
AZURE_DEVOPS_ORG: "hpswapps"
AZURE_DEVOPS_PROJECT: "Phoenix-DS%20Platform"
AZURE_DEVOPS_WIKI_IDENTIFIER: "Phoenix-DS-Platform.wiki"

# proxy is used to set the HTTPS_PROXY environment variable when necessary.
# For example, if you need to access Galileo from a restricted network,
# you should specify the proxy in this config.yaml file.
# proxy: "http://web-proxy.austin.hp.com:8080"
